site_name: Koodu
site_url: https://gmwa.github.io/koodu/
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
repo_name: GMWA/koodu
repo_url: https://github.com/GMWA/koodu
nav:
  - Home: index.md
  - Install: install.md
  - Koodu Generator: generator.md
  - Testing: testing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - codehilite
