name: api
templates:
  - template-path: models.jinja
    file-path: /
    path: /
    name: model
    file-name: models
    type: py
    is-base: False
    is-macro: False
  - template-path: controllers.jinja
    file-path: /
    path: /
    name: controller
    file-name: controllers
    type: py
    is-base: False
    is-macro: False