name: api
templates:
  - template-path: models.jinja
    file-path: /
    path: /models
    name: model
    file-name: models
    type: py
    is-base: False
    is-macro: False
  - template-path: controllers.jinja
    file-path: /
    path: /models
    name: controller
    file-name: controllers
    type: py
    is-base: False
    is-macro: False
  - template-path: database.jinja
    file-path: /
    path: /models
    name: database
    file-name: database
    type: sql
    is-base: False
    is-macro: False
  - template-path: parser.jinja
    file-path: /
    path: /models
    name: parser
    file-name: parser
    type: py
    is-base: False
    is-macro: False