name: django
templates:
  - template_path: requirements.jinja
    file_path: /
    path: /
    name: requirements
    file_name: requirements
    type: txt
    is_base: False
    is_macro: False
  - template_path: manage.jinja
    file_path: /
    path: /
    name: manage
    file_name: manage
    type: py
    is_base: False
    is_macro: False
  - template_path: asgi.jinja
    file_path: /config/
    path: /
    name: asgi
    file_name: asgi
    type: py
    is_base: False
    is_macro: False
  - template_path: wsgi.jinja
    file_path: /config/
    path: /
    name: wsgi
    file_name: wsgi
    type: py
    is_base: False
    is_macro: False
  - template_path: settings.jinja
    file_path: /config/
    path: /
    name: settings
    file_name: settings
    type: py
    is_base: False
    is_macro: False
  - template_path: confinit.jinja
    file_path: /config/
    path: /
    name: init
    file_name: __init__
    type: py
    is_base: False
    is_macro: False
  - template_path: confurls.jinja
    file_path: /config/
    path: /
    name: confurls
    file_name: urls
    type: py
    is_base: False
    is_macro: False
  - template_path: confviews.jinja
    file_path: /config/
    path: /
    name: confviews
    file_name: views
    type: py
    is_base: False
    is_macro: False
  - template_path: apiadmin.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apiadmin
    file_name: admin
    type: py
    is_base: False
    is_macro: False
  - template_path: apiapps.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apps
    file_name: apps
    type: py
    is_base: False
    is_macro: False
  - template_path: apiinit.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apiinit
    file_name: __init__
    type: py
    is_base: False
    is_macro: False
  - template_path: apimodels.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apimodels
    file_name: models
    type: py
    is_base: False
    is_macro: False
  - template_path: apiserializers.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apiserializers
    file_name: serializers
    type: py
    is_base: False
    is_macro: False
  - template_path: apitests.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apitests
    file_name: tests
    type: py
    is_base: False
    is_macro: False
  - template_path: apiurls.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apiurls
    file_name: urls
    type: py
    is_base: False
    is_macro: False
  - template_path: apiviews.jinja
    file_path: /{{full_model.name.lower()}}/
    path: /
    name: apiviews
    file_name: views
    type: py
    is_base: False
    is_macro: False
  - template_path: apimigrationsinit.jinja
    file_path: /{{full_model.name.lower()}}/migrations/
    path: /
    name: apimigrationsinit
    file_name: __init__
    type: py
    is_base: False
    is_macro: False
  - template_path: readme.jinja
    file_path: /
    path: /
    name: readme
    file_name: README
    type: md
    is_base: False
    is_macro: False
