name: fastapi
templates:
  - template-path: manage.jinja
    file-path: /
    path: /
    name: manage
    file-name: manage
    type: py
    is-base: False
    is-macro: False
  - template-path: database.jinja
    file-path: /
    path: /{{app_name}}/
    name: database
    file-name: database
    type: py
    is-base: False
    is-macro: False
  - template-path: dependencies.jinja
    file-path: /
    path: /{{app_name}}/
    name: dependencies
    file-name: dependencies
    type: py
    is-base: False
    is-macro: False
  - template-path: main.jinja
    file-path: /
    path: /{{app_name}}/
    name: main
    file-name: main
    type: py
    is-base: False
    is-macro: False
  - template-path: models.jinja
    file-path: /
    path: /{{app_name}}/
    name: models
    file-name: models
    type: py
    is-base: False
    is-macro: False
  - template-path: routers.jinja
    file-path: /routers/
    path: /{{app_name}}/routers/
    name: routers
    file-name: routers
    type: py
    is-base: False
    is-macro: False
  - template-path: schemas.jinja
    file-path: /schemas/
    path: /{{app_name}}/schemas/
    name: schemas
    file-name: schemas
    type: py
    is-base: False
    is-macro: False