name: Buid and Deploy Docs

on:
  pull_request:
    branches:
    - main

permissions:
    contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      # build and deploy docs
      - run: pip install mkdocs mkdocs-material mkdocs-material-extensions
      - run: mkdocs gh-deploy --force --clean --verbose
